import { db } from '@/lib/db-sqlite';

// Static diagnostic data — auto-seeded on first login if table is empty
const DIAGNOSTICS = [
  // ===== TPE Dark Operated =====
  { tagType: 'TPE Dark Operated', failureMode: 'No response', diagnosticSteps: `# TPE Dark Operated — No Response\n\n## Quick Checks\n1. Verify 24V power is present at the sensor terminals\n2. Check the sensor indicator LED — it should be **OFF** in the normal (dark) state\n3. Confirm wiring polarity: Brown = +24V, Blue = 0V, Black = Signal\n\n## Wiring\n- Disconnect the sensor cable at the device end\n- Measure continuity from the sensor connector back to the IO module terminal\n- Check for damaged or pinched cable along the run\n\n## Sensor\n- Verify the sensor is aimed correctly at the target area\n- Clean the sensor lens — dust or debris can block the beam\n- Check sensing distance — TPE sensors typically have 0.5–2m range\n- Try swapping with a known-good sensor to isolate the issue\n\n## IO Module\n- Check the channel LED on the IO module — it should react when sensor state changes\n- Verify the IO module is online (no fault LEDs)\n- Check the slot/channel assignment matches the PLC program` },
  { tagType: 'TPE Dark Operated', failureMode: 'Stuck ON', diagnosticSteps: `# TPE Dark Operated — Stuck ON\n\nThe sensor is reporting active (beam blocked) but nothing is in the sensing area.\n\n## Quick Checks\n1. Check for obstructions in the beam path — debris, tape, misaligned brackets\n2. Clean the sensor lens\n3. Check the sensor indicator LED — if it's ON with no target, the sensor may be faulty\n\n## Alignment\n- Verify reflector (if retro-reflective) is aligned and clean\n- Check mounting bracket — vibration may have shifted the sensor\n\n## Electrical\n- Measure signal wire voltage at the IO module terminal\n- If voltage is present with sensor disconnected, check for a short in the cable\n- Try a known-good sensor\n\n## PLC Program\n- Verify the tag is not inverted in the PLC logic\n- Dark operated means the signal should be TRUE when beam is **blocked**, FALSE when clear` },
  { tagType: 'TPE Dark Operated', failureMode: 'Intermittent', diagnosticSteps: `# TPE Dark Operated — Intermittent\n\nSignal is flickering or dropping out randomly.\n\n## Quick Checks\n1. Check all cable connections — loose connectors are the #1 cause\n2. Look for cable damage — especially near moving parts or sharp edges\n3. Check for electrical noise sources nearby (VFDs, welders, solenoids)\n\n## Mechanical\n- Tighten all mounting hardware — vibration causes intermittent connections\n- Check the cable routing — avoid running parallel to power cables\n- Verify the target is stable and not vibrating through the sensing area\n\n## Electrical\n- Wiggle the connector while monitoring the signal — if it drops, replace the cable\n- Measure signal voltage under load — should be clean 0V or 24V, not floating\n- Check grounding of the sensor shield wire` },
  { tagType: 'TPE Dark Operated', failureMode: 'Other', diagnosticSteps: `# TPE Dark Operated — Other Issue\n\nIf none of the standard failure modes apply:\n\n1. Document the exact behavior you're observing\n2. Note any patterns — does it happen at certain times, after certain events?\n3. Check the PLC program for any logic that might override or mask the signal\n4. Verify the tag type assignment is correct — is this actually a TPE Dark Operated device?\n5. Escalate to engineering with your observations` },

  // ===== BCN 24V Segment 1 =====
  { tagType: 'BCN 24V Segment 1', failureMode: 'No response', diagnosticSteps: `# BCN 24V Segment 1 — No Response\n\nBeacon stack bottom segment (24V hardwired) is not responding.\n\n## Quick Checks\n1. Visually confirm the beacon is not illuminated\n2. Check 24V power at the beacon base terminal block\n3. Verify the correct segment — Segment 1 is the **bottom** segment\n\n## Wiring\n- Check the terminal block connections at the base of the beacon stack\n- Trace the wire from the IO module to the beacon — look for breaks or loose terminals\n- Measure voltage at the beacon terminal while the output is commanded ON\n\n## IO Module\n- Verify the output channel LED on the IO module lights up when commanded\n- Check if other outputs on the same module work — if none work, the module may be faulted\n- Verify slot/channel matches PLC program\n\n## Beacon\n- If voltage is present at the beacon but no light, the segment bulb/LED may be burned out\n- Try swapping segments to confirm — move segment 1 to segment 2 position\n- Check the DIP switches on the **bottom** of segment 1` },
  { tagType: 'BCN 24V Segment 1', failureMode: 'Wrong color', diagnosticSteps: `# BCN 24V Segment 1 — Wrong Color\n\nBeacon segment illuminates but shows the wrong color.\n\n## Quick Checks\n1. Verify which segment is physically installed in position 1 (bottom)\n2. Check the DIP switch settings on the bottom of the segment\n3. Confirm the bill of materials matches what's installed\n\n## DIP Switches (Bottom of Segment)\n- Refer to the beacon manufacturer documentation for DIP switch color codes\n- Common Patlite settings:\n  - SW1=OFF, SW2=OFF → Red\n  - SW1=ON, SW2=OFF → Amber\n  - SW1=OFF, SW2=ON → Green\n  - SW1=ON, SW2=ON → Blue\n\n## Resolution\n- Adjust DIP switches to the correct color\n- Or swap the physical segment with the correct color module` },
  { tagType: 'BCN 24V Segment 1', failureMode: 'Other', diagnosticSteps: `# BCN 24V Segment 1 — Other Issue\n\n1. Document the exact symptom (dim, flickering, wrong pattern, etc.)\n2. Check all mechanical connections — beacon segments stack and twist-lock\n3. Verify DIP switch positions on the bottom of the segment\n4. Try the segment in a different position on the stack\n5. Escalate if unresolved` },

  // ===== BCN I/O Link Segment 1 =====
  { tagType: 'BCN I/O Link Segment 1', failureMode: 'No response', diagnosticSteps: `# BCN I/O Link Segment 1 — No Response\n\nBeacon stack bottom segment (IO-Link controlled) is not responding.\n\n## Quick Checks\n1. Check the IO-Link master port LED — should show active communication\n2. Verify 24V power is present at the beacon base\n3. Confirm the IO-Link master port is configured for the correct device profile\n\n## IO-Link Communication\n- Check the IO-Link master diagnostics in the PLC program\n- Verify the port assignment and device ID match the beacon\n- If the port shows "no device," check the M12 cable connection\n- Try a different IO-Link port to isolate master vs device issue\n\n## Wiring\n- Inspect the M12 connector at both ends (IO-Link master and beacon)\n- Check for bent pins in the M12 connector\n- Try a known-good IO-Link cable\n\n## Beacon\n- IO-Link beacons require proper parameterization\n- Check if the beacon responds to a manual IO-Link port reset` },
  { tagType: 'BCN I/O Link Segment 1', failureMode: 'Communication error', diagnosticSteps: `# BCN I/O Link Segment 1 — Communication Error\n\nIO-Link master reports communication issues with the beacon.\n\n## Quick Checks\n1. Check IO-Link master port diagnostics for specific error codes\n2. Reseat the M12 connector at both ends\n3. Check cable length — IO-Link max cable length is 20m\n\n## Common IO-Link Errors\n- **Port not configured**: Set the IO-Link master port to IO-Link mode (not SIO or DI)\n- **Device mismatch**: The device ID doesn't match what the master expects\n- **Cable fault**: Try a different cable\n- **Parameter error**: The beacon may need re-parameterization after replacement\n\n## Resolution\n- Reset the IO-Link port from the PLC program or web interface\n- Re-download IO-Link parameters to the device\n- If persistent, replace the beacon and re-parameterize` },
  { tagType: 'BCN I/O Link Segment 1', failureMode: 'Other', diagnosticSteps: `# BCN I/O Link Segment 1 — Other Issue\n\n1. Check IO-Link master diagnostics for detailed error information\n2. Verify the IO-Link device profile and parameters are correct\n3. Document the exact behavior and any error codes\n4. Escalate to controls engineering` },

  // ===== Button Press =====
  { tagType: 'Button Press', failureMode: 'No response', diagnosticSteps: `# Button Press — No Response\n\nPushbutton input does not register when pressed.\n\n## Quick Checks\n1. Press the button firmly — some buttons require deliberate force\n2. Check the indicator LED on the IO module channel while pressing\n3. Verify 24V is present at the button terminal\n\n## Wiring\n- Check terminal connections at the button and at the IO module\n- Measure continuity through the button contacts (normally open)\n- Press the button while measuring — resistance should drop to near 0Ω\n- Check for broken wires, especially at flex points near the button\n\n## Button\n- Inspect the button mechanism — stuck, damaged, or contaminated contacts\n- Try pressing from different angles — mechanical binding can prevent actuation\n- Check if the button contact block is properly seated on the operator\n- Try a known-good contact block\n\n## IO Module\n- If the LED doesn't light with a jumper wire across the input terminals, the module channel may be faulty\n- Check module power and communication status` },
  { tagType: 'Button Press', failureMode: 'Stuck ON', diagnosticSteps: `# Button Press — Stuck ON\n\nInput shows active without the button being pressed.\n\n## Quick Checks\n1. Check if the button is physically stuck in the pressed position\n2. Disconnect the wire at the IO module — if signal clears, the issue is in the field wiring\n3. If signal persists with wire disconnected, the IO module channel may be faulty\n\n## Mechanical\n- Clean around the button — debris can hold it in\n- Check the contact block mounting — it may be misaligned and pressing the contacts\n- Verify the correct contact block type (NO vs NC) matches the application\n\n## Electrical\n- Check for shorts in the cable — especially where wires run together\n- Verify no other signal is back-feeding into this channel` },
  { tagType: 'Button Press', failureMode: 'Intermittent', diagnosticSteps: `# Button Press — Intermittent\n\nButton sometimes registers, sometimes doesn't.\n\n## Quick Checks\n1. Tighten all terminal connections\n2. Check the contact block seating on the button operator\n3. Wiggle the cable while monitoring — intermittent = loose connection\n\n## Common Causes\n- Worn button contacts — replace the contact block\n- Loose terminal screws — retorque\n- Cable damage at flex point — reroute or replace\n- Contaminated contacts — clean with contact cleaner` },
  { tagType: 'Button Press', failureMode: 'Other', diagnosticSteps: `# Button Press — Other Issue\n\n1. Document the exact behavior\n2. Check if the issue is mechanical (button) or electrical (wiring/module)\n3. Verify the PLC program logic for this input\n4. Escalate if unresolved` },

  // ===== Button Press Normally Closed =====
  { tagType: 'Button Press Normally Closed', failureMode: 'No response', diagnosticSteps: `# Button Press Normally Closed — No Response\n\nNC pushbutton input does not change state when pressed.\n\n**Important:** NC buttons read TRUE in the normal (unpressed) state and FALSE when pressed.\n\n## Quick Checks\n1. Confirm the current PLC state — it should be TRUE (1) when the button is NOT pressed\n2. Press the button — the state should go FALSE (0)\n3. If the state is already FALSE with the button released, check for an open circuit\n\n## Wiring\n- NC buttons must form a complete circuit in the normal state\n- Measure voltage at the IO module — should be ~24V with button released, ~0V when pressed\n- Check for an open circuit: broken wire, loose terminal, or bad contact block\n\n## Button\n- Verify the contact block is NC type (usually marked NC or has specific color coding)\n- A common mistake is installing a NO contact block where NC is needed\n- Check if the contact block is properly seated on the button operator` },
  { tagType: 'Button Press Normally Closed', failureMode: 'Stuck ON', diagnosticSteps: `# Button Press Normally Closed — Stuck ON\n\nNC button always reads TRUE — pressing it doesn't change the state.\n\n## Quick Checks\n1. The normal state for NC IS true — verify you're actually pressing the button fully\n2. Check the IO module LED — it should turn OFF when button is pressed\n3. Disconnect the field wire at the IO module — input should go FALSE. If it stays TRUE, module issue.\n\n## Mechanical\n- Button may not be actuating the NC contact block — check alignment\n- The contact block spring may be broken — replace the contact block\n- Verify correct contact block type is installed (NC, not NO)\n\n## Electrical\n- Check if something else is feeding 24V to this input (back-feed)\n- Measure voltage with button pressed — if still 24V, the NC contacts aren't opening` },
  { tagType: 'Button Press Normally Closed', failureMode: 'Other', diagnosticSteps: `# Button Press Normally Closed — Other Issue\n\n1. Remember: NC buttons are TRUE when released, FALSE when pressed\n2. Document the exact behavior vs expected behavior\n3. Verify NC vs NO contact block installation\n4. Check PLC logic for inversions\n5. Escalate if unresolved` },

  // ===== Button Light =====
  { tagType: 'Button Light', failureMode: 'No response', diagnosticSteps: `# Button Light — No Response\n\nIlluminated pushbutton light does not turn on when commanded.\n\n## Quick Checks\n1. Verify the PLC is commanding the output ON — check the output channel LED on the IO module\n2. Check 24V power at the button light terminal\n3. Confirm you're checking the correct button — the light is a separate output from the button press input\n\n## Wiring\n- The button light circuit is typically separate from the button contact circuit\n- Trace the output wire from the IO module to the button light terminal\n- Measure voltage at the button while the output is commanded ON\n- Check for broken wires or loose terminals\n\n## Button Light\n- If 24V is present but no light, the LED/bulb in the button may be burned out\n- Check if the light module is properly seated in the button operator\n- Try a known-good light module\n\n## IO Module\n- Verify the output channel is working — try commanding a different output on the same module\n- Check module fault status\n- Verify slot/channel assignment in PLC program` },
  { tagType: 'Button Light', failureMode: 'Stuck ON', diagnosticSteps: `# Button Light — Stuck ON\n\nButton light stays illuminated when it should be off.\n\n## Quick Checks\n1. Verify the PLC is NOT commanding the output ON — check the output tag value\n2. Check the IO module output LED — if it's OFF but the light is ON, there may be a back-feed\n\n## Electrical\n- Disconnect the output wire at the IO module — if the light stays on, 24V is coming from somewhere else\n- Check for shorts between the output wire and adjacent 24V wires in the same cable\n- Verify the output module type — some modules have leakage current that can illuminate LEDs\n\n## PLC Program\n- Check all logic that controls this output — another rung may be latching it ON\n- Verify the correct tag address is being used` },
  { tagType: 'Button Light', failureMode: 'Wrong color', diagnosticSteps: `# Button Light — Wrong Color\n\nButton illuminates but in the wrong color.\n\n## Quick Checks\n1. Verify which LED module is installed in the button\n2. Check if this is a multi-color LED button — some have multiple inputs for different colors\n3. Confirm the bill of materials for the correct LED color\n\n## Resolution\n- Replace the LED module with the correct color\n- If multi-color, verify the PLC is commanding the correct output for the desired color\n- Check if LED modules were swapped between buttons during installation` },
  { tagType: 'Button Light', failureMode: 'Intermittent', diagnosticSteps: `# Button Light — Intermittent\n\nButton light flickers or turns on/off randomly.\n\n## Quick Checks\n1. Check if the PLC output is stable — monitor the tag value for fluctuations\n2. Tighten all terminal connections\n3. Check the LED module seating in the button\n\n## Common Causes\n- Loose LED module — reseat it firmly\n- Loose terminal connection — retorque screws\n- Overloaded output channel — check current draw vs module rating\n- Failing LED module — replace` },
  { tagType: 'Button Light', failureMode: 'Other', diagnosticSteps: `# Button Light — Other Issue\n\n1. Document the exact symptom (dim, wrong pattern, etc.)\n2. Verify the output is being commanded correctly from the PLC\n3. Check all connections from IO module to button\n4. Try a known-good LED module\n5. Escalate if unresolved` },
];

let seeded = false;

/**
 * Auto-seed diagnostic data if the table is empty.
 * Called once on first login — idempotent.
 */
export async function ensureDiagnosticData(): Promise<void> {
  if (seeded) return;
  try {
    const row = db.prepare('SELECT COUNT(*) as count FROM TagTypeDiagnostics').get() as { count: number };
    if (row.count > 0) {
      seeded = true;
      return;
    }
    const stmt = db.prepare(
      'INSERT OR IGNORE INTO TagTypeDiagnostics (TagType, FailureMode, DiagnosticSteps) VALUES (?, ?, ?)'
    );
    for (const d of DIAGNOSTICS) {
      stmt.run(d.tagType, d.failureMode, d.diagnosticSteps);
    }
    seeded = true;
    console.log(`[DB] Auto-seeded ${DIAGNOSTICS.length} diagnostic entries`);
  } catch (e) {
    console.warn('[DB] Failed to seed diagnostics:', (e as Error).message);
  }
}
