/**
 * Parse <g id="..."> elements out of an SVG string in document order.
 *
 * The SCADA team exports every device as a top-level <g> element with the
 * device name as the id (matches NetworkDeviceName in the local Ios table).
 * Their layout order on the SVG is the order they want operators to walk
 * the floor — we preserve it.
 *
 * Regex over a real XML parser is intentional: zero new deps, the SVGs are
 * machine-generated by Inkscape with predictable structure, and the only
 * thing we extract is the id attribute on <g> tags.
 */
export function parseDeviceIdsFromSvg(svg: string): string[] {
  const ids: string[] = []
  const re = /<g\b[^>]*\bid\s*=\s*(['"])([^'"]+)\1[^>]*>/g
  let m: RegExpExecArray | null
  while ((m = re.exec(svg)) !== null) {
    ids.push(m[2])
  }
  return ids
}
